// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  default: 'https://cdn.jsdelivr.net/npm/@agorapete/wllama@3.5.1-q2.0/esm/wasm/wllama.wasm',
};

export const WasmCompatFromCDN = {
  worker: 'https://cdn.jsdelivr.net/npm/@agorapete/wllama-compat@3.5.1-q2.0/wasm/wllama.js',
  wasm: 'https://cdn.jsdelivr.net/npm/@agorapete/wllama-compat@3.5.1-q2.0/wasm/wllama.wasm',
};

export default WasmFromCDN;